---
java_version: "1.8.0"
postgres_version: "9.6"
git_version: "2.14.4"
atl_shared_mountpoint: "/media/atl"

# FIXME: Some of these could be overridden from the environment.
atl_home_base: "/var/atlassian/application-data"
atl_product_home: "{{ atl_home_base }}/{{ atl_product }}"

atl_product_installation_base: "/opt/atlassian"
atl_product_installation_dir: "{{ atl_product_installation_base }}/{{ atl_product }}"
atl_installer_temp: "{{ atl_product_installation_base }}/tmp"

#  The following are imports from the environment. These are generally
#  set in /etc/atl by the CloudFormation template and sourced before
#  Ansible is run. See bin/ansible-with-atl-env for a convenient wrapper
atl_efs_id: "{{ lookup('env', 'ATL_EFS_ID') }}"

