---

# This file is the place for AWS cross-role defaults for all products, and
# common parameters from the infrastructure-deployment phase of the
# build (e.g. CloudFormation). Variables defined here will override
# those defined in `<role>/defaults/main.yml`, although defaults
# should usually be defined there too. For variable precedence
# information see:
#
#    https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html

atl_jdbc_query_params_for_engine:
  aurora_postgres: "?targetServerType=master"