---

atl_home_base: "/var/atlassian/application-data"
atl_product_home: "/home/{{ atl_product_user }}"
atl_product_home_shared: "{{ atl_product_home }}/shared"
atl_product_home_shared_download_dir: "{{ atl_product_home }}/downloads"
atl_product_shared_plugins: "{{ atl_product_home }}/plugins"

atl_installation_base: "/opt/atlassian"
atl_product_installation_base: "{{ atl_installation_base }}/{{ atl_product_edition }}"
atl_product_installation_versioned: "{{ atl_product_installation_base }}/{{ atl_product_version }}"
atl_product_installation_current: "{{ atl_product_installation_base }}/current"
atl_installer_temp: "{{ atl_installation_base }}/tmp"

atl_db_type: "postgres72"
atl_jdbc_url: "jdbc:postgresql://{{ atl_db_host }}/{{ atl_jdbc_db_name }}"
atl_db_driver: "org.postgresql.Driver"
atl_jdbc_encoding: "UTF-8"
atl_jdbc_collation: "en_US.UTF-8"
atl_jdbc_ctype: "en_US.UTF-8"
atl_jdbc_template: "template1"

atl_java_home: "{{ '/usr/lib/jvm/java' if atl_use_system_jdk else (atl_product_installation_current + '/jre') }}"
atl_java_binary: "{{ atl_java_home }}/bin/java"

atl_ssl_proxy: "false"
