---
- name: Converge
  hosts: all
  vars:
    atl_product_user: "jira"
    atl_product_family: "jira"
    atl_product_edition: "jira-software"

    atl_startup_enable: false

  pre_tasks:
    - name: Create systemd dir if necessary
      file:
        path: '/etc/systemd/system/'
        state: directory

  roles:
    - role: product_startup
