---

- name: Install Amazon-Linux-specific support packages
  yum:
    name:
      - shadow-utils
      - libxml2
      - git-{{ git_version }}
      - dejavu-sans-fonts
  vars:
    ansible_python_interpreter: auto
