---

# Note: Try and limit these to packages that are distro-specific, and
# place commonly-named ones below.
- name: Install distro-specific prerequisites
  include: "{{ ansible_distribution|lower }}.yml"

- name: Install common support packages
  package:
    name:
      - jq
      - curl
