---

- hosts: localhost
  connection: local
  vars_files: group_vars/aws_node_local.yml
  roles:
    - role: jira_zdu_init

- hosts: all
  serial: 1
  any_errors_fatal: true
  vars_files: group_vars/aws_node_local.yml
  roles:
    - role: aws_common
    - role: product_common
    - role: product_install
    - role: jira_config
    - role: product_startup

- hosts: localhost
  connection: local
  vars_files: group_vars/aws_node_local.yml
  roles:
    - role: jira_zdu_finish