---

- hosts: localhost
  connection: local
  vars_files: group_vars/aws_node_local.yml
  roles:
    - role: jira_zdu_init

- hosts: all
  serial: 1
  any_errors_fatal: true
  vars_files: group_vars/aws_node_local.yml
  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "jira"
    atl_product_user: "jira"
    atl_product_edition: "jira-{{ lookup('env', 'ATL_PRODUCT_EDITION') | lower }}"
    atl_install_jsd_as_obr: "{{ lookup('env', 'ATL_JSD_ASOBR') }}"
    atl_systemd_service_name: "jira.service"
  pre_tasks:
    - name: stop jira
      service:
        name: "{{ atl_systemd_service_name }}"
        state: stopped
  roles:
    - role: aws_common
    - role: product_common
    - role: product_install
    - role: jira_config
    - role: product_startup

- hosts: localhost
  connection: local
  vars_files: group_vars/aws_node_local.yml
  roles:
    - role: jira_zdu_finish