---
- hosts: aws_node_local
  become: true

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "jira"
    atl_product_user: "jira"
    atl_product_edition: "jira-{{ lookup('env', 'ATL_PRODUCT_EDITION') | lower }}"

  roles:
    - role: linux_common
    - role: aws_common
    - role: aws_efs_config
    - role: product_common
    - role: product_install
    - role: database_init
    # - role: jira_config
    # - role: product_startup
