---
- hosts: all
  become: true

  vars:
    atl_product_family: "jira"
    atl_product_edition: "jira-software"
    atl_product_user: "jira"

  roles:
    - linux_common
    - aws_common
    - product_common
    - aws_efs_config
    - database_config
    - jira_download
    - jira_config
