---
- hosts: all
  become: true

  vars:
    atl_product: jira
    atl_product_user: jira

  roles:
    - linux_common
    - aws_common
    - aws_linux2_product_common
    - product_base
    - aws_efs_config
