---
- hosts: azure_node_local
  become: true

  vars:
    atl_product_family: "crowd"
    atl_product_user: "crowd"
    atl_product_edition: "crowd"
    atl_use_system_jdk: true
    atl_download_format: "tarball"

    atl_startup_systemd_params:
      - "Environment=JDBC_DRIVER={{ atl_db_driver }}"
      - "Environment=JDBC_DIALECT={{atl_jdbc_dialect}}"
      - "Environment=JDBC_USER={{ atl_jdbc_user }}"
      - "Environment=JDBC_PASSWORD={{ atl_jdbc_password }}"
      - "Environment=JDBC_URL={{ atl_jdbc_url }}"

    atl_jdbc_encoding: 'UNICODE'
    atl_jdbc_collation: "{{ 'C' if atl_db_engine == 'rds_postgres' else 'Latin1_General_CS_AS' }}"
    atl_jdbc_ctype: 'C'
    atl_jdbc_template: 'template0'

  roles:
    - role: linux_common
    - role: azure_common
    - role: azure_shared_fs_config
    - role: product_common
    - role: product_install
      tags: [skip_on_stack_update]
    - role: database_init
      tags: [skip_on_stack_update]
    - role: crowd_config
    - role: azure_app_insights_install
    - role: product_startup
