---
- hosts: jira_software
  become: true

  vars:
    atl_db_host: "localhost"
    atl_jdbc_user: "jira"
    atl_jdbc_db_name: "jira"

    # Set on commandline
    # atl_jdbc_password: 
    # atl_db_root_password:

    atl_jdbc_encoding: 'UNICODE'
    atl_jdbc_collation: 'C'
    atl_jdbc_ctype: 'C'
    atl_jdbc_template: 'template0'


    atl_product_user: 'jira'
    atl_use_system_jdk: true

    atl_write_tags: false

  roles:
    - role: linux_common
    - role: aws_common
    - role: postgres_install
    - role: database_init

#    - role: product_common

    # - role: product_install
    #   tags: [skip_on_stack_update]
    #   tags: [skip_on_stack_update]
    # - role: restore_backups
    # - role: jira_config
    # - role: product_startup
