---
- hosts: localhost
  connection: local
  gather_facts: True
  become: False

  vars:
    vpc_name: "DCD-Migration-Video"
    business_unit: "Engineering-Server"
    resource_owner: "{{ ansible_user_id }}"
    aws_region: "us-west-2"

  roles:
    - { role: aws-vpc }
    - { role: ec2-instance, vars: { instance_name: "Jira Software Migration Source Instance" } }
    - { role: ec2-instance, vars: { instance_name: "Jira ServiceDesk Migration Source Instance" } }
