---

- name: Install JDK if necessary on Ubuntu
  package:
    name:
      - openjdk-{{ java_major_version }}-jdk-headless
  when: atl_use_system_jdk
  tags:
    - runtime_pkg

- name: Set java_home variable
  set_fact:
    java_home: "/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64"
  when: atl_use_system_jdk

- name: Install other base packages on Ubuntu
  package:
    name:
      - fonts-dejavu-core  # Required by installer
