---

# Amazon Linux 2 supplies extra packages via a special command.
- name: Enable Postgresql from 'extras'
  command: amazon-linux-extras install -y "postgresql{{ postgres_version }}"
  ignore_errors: yes
  environment:
    PYTHON: /bin/python
  args:
    creates: /usr/bin/psql
  environment:
    PYTHON: /bin/python
