---

- name: Perform distro-specific tasks
  include: "{{ ansible_distribution|lower }}.yml"

- name: Create product user
  user:
    name: "{{ atl_product_user }}"
    comment: "Product runtime user"

- name: Create installation directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ atl_product_user }}"
  with_items:
    - "{{ atl_product_home }}"
    - "{{ atl_installer_temp }}"
