---

- name: "Set the systemd_dir"
  set_fact:
    systemd_dir: "{% if ansible_distribution|lower=='ubuntu' %}/lib/systemd/system{% else %}/usr/lib/systemd/system{% endif %}"

- name: "systemd_dir debug"
  debug:
    msg: "systemd_dir {{ systemd_dir }}"

- name: "Install systemd service file"
  template:
    src: "product.service.j2"
    dest: "{{ systemd_dir }}/{{ atl_systemd_service_name }}"
    owner: root
    group: root
    mode: 0640
  notify:
    - Enable Product
    - Restart Product
