---
- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: wait for port 7990 to be up
  wait_for:
    port: 7990
    delay: 60

- name: wait for path to become available
  wait_for:
    path: "{{ atl_product_home_shared }}/data/migration/import"
    delay: 60

- name: Copy Bitbucket dataset from s3
  get_url:
    url: "{{ atl_bitbucket_dataset_url }}"
    dest: "{{ atl_product_home_shared }}/data/migration/import"

- name: Invoke Import API
  uri: 
    url: "{{ atl_bitbucket_dataset_url }}/rest/api/1.0/migration/imports"
    user: admin
    password: "{{ atl_bitbucket_admin_password }}"
    method: POST
    follow_redirects: yes
    force_basic_auth: yes
    creates: "{{ atl_product_home_shared }}/data/migration/import/lock.file"
    body: "{ \"archivePath\": \"{{ atl_bitbucket_dataset_url | basename }}\" }"
    body_format: json
    return_content: yes
  register: response
  until: response.status == 200
  retries: 6
  delay: 15
  failed_when: response.json.state != 'INITIALISING'

- name: get status of import
  debug: var=response


- name: get job id
  debug: var=response.json.state
  with_items: "{{ response }}"


- name: get job id
  debug: var=response.json.id
  with_items: "{{ response }}"



