---

- name: Check if import directory exists
  stat:
      path: /tmp/import
      register: import_dir

- name: create directory structure if it note exists
  file:
    path: /tmp/import
    state: directory
    mode: 0644
    group: root
    owner: root
  when: import_dir.stat.exists == false

- name: Copy Bitbucket dataset from s3
  get_url:
    url: "{{ atl_bitbucket_dataset_url }}"
    dest: /tmp/import


