---

- name: Create application DB user
  postgresql_user:
    login_host: "{{ atl_db_host }}"
    login_user: "{{ atl_db_root_user }}"
    login_password: "{{ atl_db_root_user }}"
    port: "{{ atl_db_port }}"
    name: "{{ atl_jdbc_user }}"
    password: "{{ atl_jdbc_password }}"
    expires: 'infinity'

- name: Creat application database
  postresql_db:
    login_host: "{{ atl_db_host }}"
    login_user: "{{ atl_db_root_user }}"
    login_password: "{{ atl_db_root_user }}"
    port: "{{ atl_db_port }}"
    name:  "{{ atl_jdbc_name }}"
    owner:  "{{ atl_jdbc_user }}"
    encoding: "{{ atl_jdbc_encoding }}"
    lc_collate: "{{ atl_jdbc_collation }}"
    lc_ctype: "{{ atl_jdbc_ctype }}"
    template: "{{ atl_jdbc_template }}"

- name: Create dbconfig.xml
  template:
    src: dbconfig.xml.j2
    dest: "{{ atl_product_home }}/dbconfig.xml"
    owner: "{{ atl_product_user }}"
