---

- name: Install collectd for app insights
  package:
    name:
      - collectd

- name: Configure Collectd
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf
  notify:
    - Restart Collectd

- name: Change collectd.conf permissions
  file:
    path: /etc/collectd/collectd.conf
    mode: '+r'

- name: Install JAXB
  get_url:
    url: "https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/{{ app_insights_jaxb_version }}/jaxb-api-{{ app_insights_jaxb_version }}.jar"
    dest: "/usr/share/collectd/java/"

# - name: Download App Insights jars
#  get_url:
#    url: "https://github.com/Microsoft/ApplicationInsights-Java/releases/download/{{ app_insights_version }}/{{ item }}"
#    dest: "{{ atl_product_installation_versioned }}/crowd-webapp/WEB-INF/lib/"
#  with_items:
#    - "applicationinsights-core-{{ app_insights_version }}.jar"
#    - "applicationinsights-web-{{ app_insights_version }}.jar"
#    - "applicationinsights-collectd-{{ app_insights_version }}.jar"
#
# - name: Copy applicationinsights-collectd to collectd
#  copy:
#    src: "{{ atl_product_installation_versioned }}/crowd-webapp/WEB-INF/lib/applicationinsights-collectd-{{ app_insights_version }}.jar"
#    dest: "/usr/share/collectd/java/applicationinsights-collectd-{{ app_insights_version }}.jar"
#    remote_src: true
#
# - name: Add ApplicationInsights.xml configuration
#  template: src=ApplicationInsights.xml.j2 dest={{ atl_product_installation_versioned }}/crowd-webapp/WEB-INF/classes/ApplicationInsights.xml

- name: Download applicationinsights-collectd to collectd
  get_url:
    url: "https://github.com/Microsoft/ApplicationInsights-Java/releases/download/{{ app_insights_version }}/{{ item }}"
    dest: "/usr/share/collectd/java/applicationinsights-collectd-{{ app_insights_version }}.jar"
  with_items:
    - "applicationinsights-collectd-{{ app_insights_version }}.jar"
