---

- name: Fetch and cache latest version when no override
  get_url:
    url: "{{ atl_product_latest_version_url }}"
    dest: "{{ atl_product_version_cache }}"
    force: false
  when: atl_product_version is undefined or atl_product_version == "latest"

- name: Write override cached version when specified
  template:
    src: version.j2
    dest: "{{ atl_product_version_cache }}"
    force: false
  when: atl_product_version is defined and atl_product_version != "latest"

- name: Use version for product version
  command: "cat {{ atl_product_version_cache }}"
  register: atl_product_version_file

- name: Fetch product installer
  get_url:
    url: "{{ atl_product_download_url }}"
    dest: "{{ atl_product_download_cache }}"
    mode: 0755
    force: false
