---

- name: Fetch and cache latest version when no override
  get_url:
    url: "{{ atl_product_latest_version_url }}"
    dest: "{{ atl_product_version_cache }}"
    force: false
  when: atl_product_version is undefined or atl_product_version == "latest"

- name: Write override cached version when specified
  template:
    src: version.j2
    dest: "{{ atl_product_version_cache }}"
    force: false
  when: atl_product_version is defined and atl_product_version != "latest"

- name: Use version for product version
  command: "cat {{ atl_product_version_cache }}"
  register: atl_product_version_file
  changed_when: False

# Note: We don't cache this in the shared drive to the complexity
# around download race-conditions if multiple nodes are starting at
# the same time. When downloading from product-downloads.atlassian.com
# (which is a CDN) takes seconds anyway.
- name: Fetch product installer
  get_url:
    url: "{{ atl_product_download_url }}"
    dest: "{{ atl_product_download }}"
    mode: 0755
    force: false
