---

- name: Add atlassian-slingshot yum repository
  yum_repository:
    name: AtlassianSlingshot
    file: atlassian-slingshot
    state: present
    description: Atlassian Slingshot
    baseurl: "{{ atl_slingshot_yum_repo_url }}"
    gpgcheck: no
  vars:
    ansible_python_interpreter: auto  

- name: Install atlassian-slingshot
  yum:
    name: atlassian-slingshot
  vars:
    ansible_python_interpreter: auto

- name: Enable Postgresql from 'extras'
  command: amazon-linux-extras install -y "postgresql{{ atl_amazon_extras_postgresql_version }}"
  args:
    creates: /usr/bin/psql
  environment:
    PYTHON: /bin/python
