---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu_lts
    image: ubuntu:bionic
    groups:
      - azure_node_local
provisioner:
  name: ansible
  options:
    skip-tags: runtime_pkg
  lint:
    name: ansible-lint
    options:
      x: ["701"]
  inventory:
    links:
      group_vars: ../../../../group_vars/
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
