---

- name: Create mountpoint
  file:
    state: directory
    path: "{{ atl_shared_mountpoint }}"
    mode: 0755

- name: Enable mountpoint in fstab
  mount:
    path: "{{ atl_shared_mountpoint }}"
    src: "{{ efs_target }}:/"
    fstype: efs
    opts: "defaults,_netdev"
    state: mounted
  ignore_errors: yes
