---

- name: Create mountpoint
  file:
    state: directory
    path: "{{ atl_shared_mountpoint }}"
    owner: "{{ atl_product_user }}"
    mode: 0755

- name: Enable mountpoint in fstab
  mount:
    path: "{{ atl_shared_mountpoint }}"
    src: "{{ efs_target }}:/"
    fstype: nfs4
    opts: "rw,vers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
    state: mounted
